let a=10;
let b=20;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a%b);
console.log("*****************COMPARISION OPERATOR*******************");
console.log(a==b);
console.log(a===b);
console.log(a>b);
console.log(a<b);
console.log(a>=b);
console.log(a<=b);
console.log(a!=b);
console.log("********************LOGICAL OPERAYTOR******************");
let age=17;
let hasId=true;
console.log(age>18&&hasId);
console.log(age>18||hasId);
console.log("******************** ASSIGNMENT OPERATOR ***************");
console.log(a+=b);
console.log(a-=b);
console.log(a*=b);
console.log(a/=b);
console.log(a%=b);
